# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CzipCompressor < Formula
  desc "czip: EVM Calldata Zip"
  homepage "https://github.com/0xsequence/czip"
  version "0.2.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xsequence/czip/releases/download/v0.2.4/czip-compressor.darwin-amd64"
      sha256 "85463f078c956f68a41c68a453bc532f1d526ec14c166697914b550e3ecd054c"

      def install
        bin.install "czip-compressor.darwin-amd64" => "czip-compressor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xsequence/czip/releases/download/v0.2.4/czip-compressor.darwin-arm64"
      sha256 "06a7512f5a51b34ec6ace979c34661afe67f026fa98c0f828144682cc7c7fdd2"

      def install
        bin.install "czip-compressor.darwin-arm64" => "czip-compressor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/0xsequence/czip/releases/download/v0.2.4/czip-compressor.linux-amd64"
      sha256 "10e8a92d7ffecc2bbd617cc2ad761a77faace51f3597cb8fe9ace2ae206694ad"

      def install
        bin.install "czip-compressor.linux-amd64" => "czip-compressor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xsequence/czip/releases/download/v0.2.4/czip-compressor.linux-arm64"
      sha256 "fb31b26f2eb75359869348a4ef01f54b8343cf7a9a914eaf4b6bdc325c377747"

      def install
        bin.install "czip-compressor.linux-arm64" => "czip-compressor"
      end
    end
  end
end
